services:
  eth-predictor:
    build: .
    container_name: eth-whale-predictor
    ports:
      - "9696:9696"
    environment:
      - DUNE_WHALES_API=D1Smlg20H9BwjVTPpN8kGjdg2MZyIvuM
      - COINGECKO_API_KEY=CG-nm5ynnbGBWTugQhVY2vNMWbP
      - ADMIN_API_KEY=ML-WhalesMoves82m1960
      - PYTHONUNBUFFERED=1
    volumes:
      - ./prediction_cache.json:/app/prediction_cache.json
      - ./whale_prices_ml_ready.csv:/app/whale_prices_ml_ready.csv
    restart: unless-stopped